config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'posts#index'
  shallow do
    resources :posts do
      resources :likes
    end
  end

  resources :comments, :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= nil
    if user.nil?
      can :read, :all
      cannot [:new, :create, :destroy, :edit, :update], Post
    else
      can :read, :all
      can :create, Post
      can [:update, :destroy], Post, :user_id => user.id
      can :create, Like
      can :destroy, Comment, :user_id => user.id
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "400x400>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :user
  has_many :likes
  has_many :comments

  def self.filter_by_hashtag(hashtag)
    return Post.where("message LIKE \"%#{hashtag}%\"").order("created_at DESC").uniq
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    user_id = params[:user_id] if !params[:user_id].blank?
    if user_id
      post = Post.find(params[:post_id])
      comment = post.comments.create(content: params[:content], user_id: user_id)
      render json: { content: comment.content, username: comment.user.username, comment_id: comment.id }
    else
      render json: { error: "Could not create comment" }
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    if current_user && comment && comment.user_id == current_user.id
      comment.destroy!
      render json: nil, status: :ok
    else
      render json: nil, status: :error
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    if user_signed_in?
      existing_like = @post.likes.where(user_id: current_user.id).first
      if !existing_like
        Like.create(post_id: @post.id, user_id: current_user.id)
        liked = true
      else
        existing_like.destroy!
        liked = false
      end
    end
    render json: { new_like_count: @post.likes.count, liked: liked }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    search = params[:search] if params[:search] && !params[:search].blank?
    if search
      @posts = Post.filter_by_hashtag(search)
    else
      @posts = Post.order("id DESC")
    end
    respond_to do |format|
      format.json { render json: {posts: @posts.distinct} }
      format.html { render 'index'}
    end
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    respond_to do |format|
      format.json { render json: {
        post: @post, comments: @post.comments, likes: @post.likes}
      }
      format.html { render 'index' }
    end
  end

  def edit
  end

  def create
    if current_user
      @post = Post.new(post_params)
      @post.user_id = current_user.id
    end
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
      else
        format.html { render :new, notice: 'There was a problem.' }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, notice: 'Success!' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Poof! That post is history.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params[:post].permit(:image, :message)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hashtagify(string)
    string.gsub(/(?:#(\w+))/) {link_to_hashtag($1)}
  end

  def link_to_hashtag(string)
    link_to "##{string}", posts_path(search: string)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
%html{'ng-app': 'picturegram'}
  %head
    %title
      picturegram
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    #main-nav
      %a#home_button{:href => "/"}
        %h2.text-center
          picture
          %i.fa.fa-camera
          gram
      .pull-right.nav-buttons
        -if user_signed_in?
          =link_to "Add a Post", new_post_path, :class => 'btn btn-primary'
          =link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'btn btn-primary'
        -else
          =link_to "Sign In", new_user_session_path, :class => 'btn btn-primary'
          =link_to "Sign Up", new_user_registration_path, :class => 'btn btn-primary'
    .content.col-md-6.col-md-push-3
      %p.notice= notice
      %p.alert= alert
      = yield

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
  <% if @like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% @like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/new.html.erb
<h1>New like</h1>

<%= render 'form' %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  #upload.text-center
    = f.label :image, "Upload new photo"
    %br
    .image_upload
      = f.file_field :image
    %img.upload_preview{src: ""}
    %br
    = f.text_field :message, label: false, placeholder: "Say some words."
    %br
    = f.submit :value => "Post It!", :class => 'btn btn-primary'

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.haml
.text-center
  = form_tag posts_path, :method => 'get', :id => "index_search" do
    = text_field_tag :search, params[:search], :placeholder=> "Search", class: "search-box", id: "search"
    = button_tag(type: "submit", class: "btn search-btn") do
      %i.fa.fa-search

%post-list
-# -if @posts.any?
-#   -@posts.each do |post|
-#     %post-display{post: post.to_json}
    -# .row.post_display
    -#   .post_image.col-md-12=image_tag(post.image.url(:large))
    -#   .col-md-6
    -#     .pull-left
    -#       -existing_like = post.likes.where(user_id: current_user.id).first if user_signed_in?
    -#       .pull-left.total_likes="#{post.likes.count}"
    -#       =link_to post_likes_path(post), class: "add-like" do
    -#         %i.fa{class: existing_like ? "fa-heart" : "fa-heart-o"}
    -#       =link_to "#", class: "add-comment" do
    -#         %i.fa.fa-comment-o
    -#   .col-md-6
    -#     .pull-right
    -#       .post_buttons
    -#         -if can? :update, post
    -#           =link_to edit_post_path(post), class: "edit-button" do
    -#             %i.fa.fa-pencil
    -#         -if can? :destroy, post
    -#           =link_to post_path(post), method: :delete, class: "delete-button" do
    -#             %i.fa.fa-trash
    -#   .col-md-12
    -#     .post_message.raleway
    -#       ="@#{post.user.username} "
    -#       = hashtagify(post.message).html_safe
    -#   .col-md-12.comment_form
    -#     %form
    -#       %textarea.new_comment{name: "new-comment", placeholder: ("You must be signed in to comment." unless current_user), data: { post_id: post.id, user_id: (current_user.id if current_user) }, disabled: !current_user}
    -#       %i.fa.fa-comment.submit-comment{disabled: !current_user}
    -#   .col-md-12.photo_comments
    -#     - post.comments.each do |comment|
    -#       .row.post_message.raleway
    -#         = "@#{comment.user.username}: "
    -#         = hashtagify(comment.content).html_safe
    -#         -if can? :destroy, comment
    -#           .pull-right
    -#             = link_to comment_path(comment), class: 'delete-comment' do
    -#               %i.fa.fa-times
-# -else
-#   %h3 No posts yet.

app/views/posts/new.html.haml
.text-center
  = link_to 'Back', posts_path
  = render 'form'

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/show.html.haml
=link_to "Edit Profile", edit_user_path(@user)